
# This is the name as it will be shown in GitHub
name: Handy components of GitHub Actions

# Run this workflow when we press the button to run it
on:
  pull_request:
    branches: [ main, staging ]
  workflow_dispatch:

# These are the jobs we wanna do
jobs:
  # This is the name of this job
  hello:
    # This is the environment we are running this on
    runs-on: ubuntu-latest
    steps:

      # What are these environment variables
      - name: Print environment variables
        run: |
          # Gonna print out the repo that this is on
          echo ${GITHUB_REPOSITORY}
          # Remember this variable GITHUB_REF changes depending on our trigger
          echo ${GITHUB_REF}

      # How to set our own variables within a setp
      - name: Hello, but make it personal
        run: echo "Hello $First_Name."
        env:
          First_Name: Candace

      # How to export a variable to a next step
      - name: Setting output to the environment at large
        id: step_name
        run: echo "results=5" >> $GITHUB_OUTPUT

      # How to print out the variable we just saved
      - name: Print out that variable in a later step
        run: echo ${{ steps.step_name.outputs.results > 3 }}

      # Maybe we only want to run a step based on the outcome of a previous step. Here's how:
      - name: Conditional step
        # Here we are only going to do this step if the results from the previous step are bigger than 3
        if: ${{ steps.step_name.outputs.results > 3 }}
        run: echo 'the results are greater than 3!'

      # Here's how we'd reference a secret
      # - name: How do we reference a GITHUB secret?
        # run: ${ secrets.SECRET_NAME }
